#pragma once
#ifndef __RENDER_BUFFER_TYPES_H__
#define __RENDER_BUFFER_TYPES_H__


enum EBufferUsage
{
    E_BUFFER_USAGE_NONE     = -1
    ,E_BUFFER_USAGE_STREAM_DRAW
    ,E_BUFFER_USAGE_STREAM_READ
    ,E_BUFFER_USAGE_STREAM_COPY
    ,E_BUFFER_USAGE_STATIC_DRAW
    ,E_BUFFER_USAGE_STATIC_READ
    ,E_BUFFER_USAGE_STATIC_COPY
    ,E_BUFFER_USAGE_DYNAMIC_DRAW
    ,E_BUFFER_USAGE_DYNAMIC_READ
    ,E_BUFFER_USAGE_DYNAMIC_COPY

    ,E_BUFFER_USAGE_COUNT
};

enum EBufferAcces
{
     E_BUFFER_ACCES_NONE     = -1
    ,E_BUFFER_ACCES_READ_ONLY
    ,E_BUFFER_ACCES_WRITE_ONLY
    ,E_BUFFER_ACCES_READ_WRITE

    ,E_BUFFER_ACCES_COUNT
};



#endif /*__RENDER_BUFFER_TYPES_H__*/