#if !defined(__KERNEL_MICROSOFT_SPECIFIC_H__)
#define __KERNEL_MICROSOFT_SPECIFIC_H__

#if defined(_MSC_VER)

#   define  THOT_COMPILER_MICROSOFT _MSC_VER
#   pragma message(THOT_COMPILE_OUTPUT_PREFIX"THOT_COMPILER_MICROSOFT")

#   define  THOT_MICROSOFT_VISUAL_STUDIO2012 1700
#   define  THOT_MICROSOFT_VISUAL_STUDIO2010 1600
#   define  THOT_MICROSOFT_VISUAL_STUDIO2008 1500
#   define  THOT_MICROSOFT_VISUAL_STUDIO2005 1400
#   define  THOT_MICROSOFT_VISUAL_STUDIO2003 1310

#   define THOT_PLATFORM_WINDOWS
#   pragma message( THOT_COMPILE_OUTPUT_PREFIX"THOT_PLATFORM_WINDOWS")


#if THOT_COMPILER_MICROSOFT>=THOT_MICROSOFT_VISUAL_STUDIO2010

#   define  THOT_ENABLE_RVALUE_REFERENCE
#   define  THOT_ENABLE_MOVE_CONSTRUCTOR
#   define  THOT_ENABLE_EXTERN_TEMPLATE

#   pragma message(THOT_COMPILE_OUTPUT_PREFIX"THOT_ENABLE_RVALUE_REFERENCE")
#   pragma message(THOT_COMPILE_OUTPUT_PREFIX"THOT_ENABLE_MOVE_CONSTRUCTOR")
#   pragma message(THOT_COMPILE_OUTPUT_PREFIX"THOT_ENABLE_EXTERN_TEMPLATE")

#endif _MSC_VER>=THOT_MICROSOFT_VISUAL_STUDIO2010*/


#   ifndef _M_IX86
#       define  THOT_PLATFORM_ARCH_X64
#       pragma message(THOT_COMPILE_OUTPUT_PREFIX"THOT_PLATFORM_ARCH_X64")
#   else
#       define  THOT_PLATFORM_ARCH_X86
#       pragma message(THOT_COMPILE_OUTPUT_PREFIX"THOT_PLATFORM_ARCH_X86")
#   endif

#if defined(UNICODE) || defined(_UNICODE)
#   define THOT_UNICODE
#   pragma message(THOT_COMPILE_OUTPUT_PREFIX"THOT UNICODE IS ENABLED")

#else
#   pragma message(THOT_COMPILE_OUTPUT_PREFIX"THOT UNICODE IS DISABLED")
#endif //defined(UNICODE) || defined(_UNICODE)



#define THOT_FORCE_INLINE       __forceinline
#define THOT_NO_INLINE          __declspec(noinline)

#   if !defined(_CRT_SECURE_NO_WARNINGS)
#       define _CRT_SECURE_NO_WARNINGS
#   endif




#else
#   error INCLUDING MicrosoftSpecific.h ON OTHER PLATFORM
#endif //_MSC_VER

#endif //__KERNEL_MICROSOFT_SPECIFIC_H__