#pragma once
#ifndef __IMAGE_TYPES_H__
#define __IMAGE_TYPES_H__

enum eImageExtension
{
     E_IMAGE_EXTENSION_NONE      = -1
    ,E_IMAGE_EXTENSION_TGA      

    ,E_IMAGE_EXTENSION_COUNT
};

enum ePixelFormat
{
    E_PIXEL_FORMAT_NONE            = -1
    ,E_PIXEL_FORMAT_RGB
    ,E_PIXEL_FORMAT_RGBA
    ,E_PIXEL_FORMAT_RED
    ,E_PIXEL_FORMAT_GREEN
    ,E_PIXEL_FORMAT_BLUE
    ,E_PIXEL_FORMAT_ALPHA
    ,E_PIXEL_FORMAT_LUMINANCE
    ,E_PIXEL_FORMAT_LUMINANCE_ALPHA
    ,E_PIXEL_FORMAT_STENCIL_INDEX
    ,E_PIXEL_FORMAT_DEPTH_COMPONENT


    ,E_PIXEL_FORMAT_COUNT
    ,E_PIXEL_FORMAT_FORCE_DWORD = 0x7fffffff
};


enum ePixelType
{
     E_PIXEL_TYPE_NONE            = -1
    ,E_PIXEL_TYPE_BITMAP
    ,E_PIXEL_TYPE_BYTE
    ,E_PIXEL_TYPE_UNSIGNED_BYTE
    ,E_PIXEL_TYPE_SHORT
    ,E_PIXEL_TYPE_UNSIGNED_SHORT
    ,E_PIXEL_TYPE_INT
    ,E_PIXEL_TYPE_UNSIGNED_INT
    ,E_PIXEL_TYPE_FLOAT
    //,E_PIXEL_TYPE_UNSIGNED_BYTE_3_3_2
    //,E_PIXEL_TYPE_UNSIGNED_BYTE_3_3_2_REV
    //,E_PIXEL_TYPE_UNSIGNED_SHORT_5_6_5
    //,E_PIXEL_TYPE_
    //,E_PIXEL_TYPE_
    //,E_PIXEL_TYPE_
    //,E_PIXEL_TYPE_
    //,E_PIXEL_TYPE_
    //,E_PIXEL_TYPE_

    ,E_PIXEL_TYPE_COUNT
};

#endif /*__IMAGE_TYPES_H__*/