#if !defined(__KERNEL_MEMORY_DEFINES_H__)
#define __KERNEL_MEMORY_DEFINES_H__

#include "Kernel/Config.h"

#if defined(THOT_ENABLE_DEBUG_MEMORY)
#   define THOT_ENABLE_HANDLE_MEMORY_OPERATION

#   if defined(THOT_ENABLE_HANDLE_MEMORY_OPERATION)
#       define THOT_ENABLE_MEMORY_TRACKING
#       define THOT_ENABLE_MEMORY_STATISTICS
//#       define THOT_CATCH_MEMORY_OPERATION_STACK
#   endif //THOT_ENABLE_HANDLE_MEMORY_OPERATION

#endif



#endif //__KERNEL_MEMORY_DEFINES_H__